name: Push Container to Azure ContainerRegistry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.containersample.azure.io }} # {mycontainer}.azurecr.io
      USERNAME: ${{ secrets.containersample }}
      IMAGE_NAME: sample-django-webapps
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker login ${REGISTRY_NAME} -u ${USERNAME} -p A36z+50wKZRalrg7yliDgrP9BdttGZqF76lTGb8IdB+ACRBp5oO4
        docker build . -t ${REGISTRY_NAME}/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
        docker push ${REGISTRY_NAME}/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
