# パイプライン名。GitHub Actionsのタブで一覧表示される時にこの名前が出る
name: CI to Azure Container Registry

# ワークフローが実行されるトリガー条件。
# mainブランチへのpushしたときに発動させてる
on:
  push:
    branches: [main]

# ジョブの定義。ビルドとプッシュを一つのジョブで実行させる
jobs:
  build:
    # 実行環境はUbuntuを指定
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }} # {mycontainer}.azurecr.io
      USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_NAME: sample-django-webapps     
    steps:
      # GitHubリポジトリのコードをチェックアウトする
      # これがないと、リポジトリのコードにアクセスできないエラーでたから要る。
      - uses: actions/checkout@v3
        name: Checkout source code

      # Dockerにログインする。ビルドとプッシュ作業の前に必要
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        
        run: | 
        docker
        docker build . -t ${REGISTRY_NAME}/sampleapp:${GITHUB_REF#refs/heads/}
        docker push ${registry}/sampleapp:${GITHUB_REF#refs/heads/}
